### ISSUE TITLE
OpenAssistant oasst1?

### ISSUE THREAD

**Issue by Interpause** [langbridgeai/Open-Instructions#1]
https://huggingface.co/datasets/OpenAssistant/oasst1

**Comment by chenz53-lb** [comment]
Thanks for the sharing. I'm looking into OpenAssistant at this moment and would include it asap. Also, given the recent releasing of DeepSpeed Chat, I am also working on integrating all these open instructions data into the unified deepspeed format so to support training across all three stages instead of just sft.

**Comment by chenz53-lb** [comment]
I'll close this thread if no other question.
